### ISSUE TITLE
node-sass -> sass

### ISSUE THREAD

**Issue by Uluer** [a631807682/ele-next#2]
建议将node-sass替换为sass。国内装node-sass太坑了！手动点星星

**Comment by a631807682** [comment]
There is still a lot of work to be done on refactoring (such as the commit message validation, issue bot, lint-staged), and I won't do it until the first release. 

----

目前关于重构还有大量的工作（除了组件代码重构，还有`commit message`检测，`issue template`，`issue robot`，`lint-staged`等一大堆东西没做），其他需求将会等到第一个release版本之后才会考虑。
