### ISSUE TITLE
执行dev失败

### ISSUE THREAD

**Issue by Uluer** [a631807682/ele-next#65]
执行dev后打开浏览器会提示。试图执行lint，但是好像每次执行都会修改文件
`
Failed to compile.

./packages/alert/src/alert.vue
Module Error (from ./node_modules/vue-loader/dist/index.js):

VueCompilerError: Element is missing end tag.
at F:\github\ele-next\packages\alert\src\alert.vue:28:9
27 |          </p>
28 |          <i
29 |            class="el-alert__closebtn"
   |                          ^
30 |            :class="{
31 |              'is-customed': closeText !== '',
`

**Comment by Uluer** [comment]
检查了标签，确实没有缺失。执行lint后再执行dev就正常

**Comment by a631807682** [comment]
可能是 `template` 在代码格式化之后 `sfc` 无法解析，有可能是 `@vue/compiler-sfc` 的问题，我会在周末看看。

**Comment by a631807682** [comment]
[vue-next/issues/1476](https://github.com/vuejs/vue-next/issues/1476)

Close by https://github.com/a631807682/ele-next/commit/f98e1a814fbab390ff220199de57f033976f98fc
