### ISSUE TITLE
作者怎么不更新了，我可以参与共享代码吗

### ISSUE THREAD

**Issue by luxueyan** [a631807682/ele-next#91]
rt，thks

**Comment by a631807682** [comment]
作为一个上班狗，实在没太多的时间更新，欢迎PR，我会尽快review。

**Comment by luxueyan** [comment]
好的 我尽力！

**Comment by zazzaz** [comment]
如果各位有兴趣 可以来一起写 我们的目标是全部重构完毕正式上线的。

https://github.com/element-plus/element-plus/

**Comment by a631807682** [comment]
有两个原因我关闭了这个项目
1. 个人没有足够的精力去完成它，按照目前的进度还要弄好久。
2. 由于`vue3`与`vue2`的差别较大，我对单纯的保持原有`api`不变的迁移的意义保持了怀疑。比如`hook`的使用，`Transition`的更改等等，都注定了有一些`api`可能可以有更好的设计。

后面还有兴趣的同学可以到 https://github.com/element-plus/element-plus 贡献代码。
